<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[openBrowser]]>
    </line>
    <line>
      <![CDATA[login]]>
    </line>
    <line>
      <![CDATA[createCustomerhas got failed]]>
    </line>
    <line>
      <![CDATA[logout]]>
    </line>
    <line>
      <![CDATA[login]]>
    </line>
    <line>
      <![CDATA[modifyCustomer]]>
    </line>
    <line>
      <![CDATA[modifyCustomerhas got success]]>
    </line>
    <line>
      <![CDATA[logout]]>
    </line>
    <line>
      <![CDATA[deleteCustomerhas got skipped]]>
    </line>
    <line>
      <![CDATA[closeBrowser]]>
    </line>
  </reporter-output>
  <suite started-at="2023-10-05T12:31:28 IST" name="Default suite" finished-at="2023-10-05T12:31:52 IST" duration-ms="24111">
    <groups>
    </groups>
    <test started-at="2023-10-05T12:31:28 IST" name="Default test" finished-at="2023-10-05T12:31:52 IST" duration-ms="24111">
      <class name="com.actitime.testscript.CustomerModule">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:28 IST" name="openBrowser" finished-at="2023-10-05T12:31:40 IST" duration-ms="12272" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[openBrowser]]>
            </line>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:40 IST" name="login" finished-at="2023-10-05T12:31:40 IST" duration-ms="370" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[login]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createCustomer()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:40 IST" name="createCustomer" finished-at="2023-10-05T12:31:40 IST" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.actitime.testscript.CustomerModule.createCustomer(CustomerModule.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createCustomerhas got failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- createCustomer -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:40 IST" name="logout" finished-at="2023-10-05T12:31:47 IST" duration-ms="6453" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[logout]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:47 IST" name="login" finished-at="2023-10-05T12:31:47 IST" duration-ms="204" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[login]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="modifyCustomer()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:47 IST" name="modifyCustomer" finished-at="2023-10-05T12:31:47 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[modifyCustomer]]>
            </line>
            <line>
              <![CDATA[modifyCustomerhas got success]]>
            </line>
          </reporter-output>
        </test-method> <!-- modifyCustomer -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:47 IST" name="logout" finished-at="2023-10-05T12:31:52 IST" duration-ms="4513" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[logout]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method signature="deleteCustomer()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:52 IST" name="deleteCustomer" finished-at="2023-10-05T12:31:52 IST" depends-on-methods="com.actitime.testscript.CustomerModule.createCustomer" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CustomerModule.deleteCustomer()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CustomerModule.deleteCustomer()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[deleteCustomerhas got skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.actitime.testscript.CustomerModule@1a451d4d]" started-at="2023-10-05T12:31:52 IST" name="closeBrowser" finished-at="2023-10-05T12:31:52 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[closeBrowser]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.actitime.testscript.CustomerModule -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
